# For simple django project without db
# pip freeze > requirements.txt to create with extensions already installed
# The first instruction is what image we want to base our container on
# We Use an official Python runtime as a parent image
FROM python:3.7

# Allows docker to cache installed dependencies between builds
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Mounts the application code to the image
COPY .. code
WORKDIR /code

EXPOSE 8000

# runs the production server
ENTRYPOINT ["python", "mysite/manage.py"]
CMD ["runserver", "0.0.0.0:8000"]


# cd project root
# docker build -t vladlength/django_dock_2 .
# docker push vladlength/django_dock_2:latest  DockerHub image pussh -->

# docker pull vladlength/django_dock_2  Download from DockerHub (pull) <--
# docker run -it -p 8000:8000 django_dock_2  RUN IMAGE --> CONTAINER localhost:8000
